name: 'solar_scada'
version: '1.0.0'
profile: 'solar_scada'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  solar_scada:
    example:
      +materialized: view
    stg:
      +materialized: view
    int:
      +materialized: view
    mart:
      +materialized: table

seeds:
  solar_scada:
    +quote_columns: false
